### ISSUE TITLE
Error while building Nuxt application

### ISSUE THREAD

**Issue by karimennassiri** [gaetansenn/xhr-cache#28]
I've installed the last version of this Module and I got an error while building my application.

**package.json**

`  "dependencies": {
    "@dewib/xhr-cache": "3.2.2"
}
`

**nuxt.config.js**

` modules: [
    '@dewib/xhr-cache'
  ],
xhrCache: {
    name: 'location',
    maxAge: 3600 * 1000,
    init: true,
    request: ({ $auth }) => ({
      method: 'get',
      url: ${process.env.API_URL}/test,
      headers: {
        'Content-Type': 'application/json',
        Authorization: $auth.strategy.token.get()
      }
    })
  },
`

**Error**

` FATAL  Cannot read property 'map' of undefined `

**Error details**

` at ModuleContainer.xhrCache (node_modules\@dewib\xhr-cache\lib\module.js:226:36)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:235:34)
  at node_modules\@nuxt\utils\dist\utils.js:1859:43
  at ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:55:5)
  at Nuxt._init (node_modules\@nuxt\core\dist\core.js:716:5)`

**Comment by gaetansenn** [comment]
Hello @karimennassiri can you push your code for instance in https://codesandbox.io/ to reproduce the bug ?

Regards,

**Comment by karimennassiri** [comment]
Hi @gaetansenn here is a link to the [codesandbox ](https://codesandbox.io/s/hungry-curran-7itw7).
I did not tested the old versions yet. 

Regards

**Comment by karimennassiri** [comment]
I can cofirm that my build completed using the 3.1.2 version. So it is an error related to the recent version and maybe the compatibilty with other dependecies.

**Comment by gaetansenn** [comment]
Look's like you configuration is not good from the codesandbox exemple:
```js
xhrCache: {
    name: "location",
    maxAge: 3600 * 1000,
    init: true
  },
```

you need to wrap it inside resources https://xhr-cache.dewib.com/api/options.html#resources
```js
xhrCache: {
  resources: [{
  name: 'my-resource'
  maxAge: 3600 * 1000, // TTL of resource
  init: true, // Fetch the resource at nuxt start
  request: {
    method: 'get',
    url: 'http://www.mocky.io/v2/5d9e4c643200002a00329d0a'
  }]
},
```

**Comment by karimennassiri** [comment]
I allow my self to correct your code
`xhrCache: {
    resources: [{
    name: 'my-resource', // correcting here
    maxAge: 3600 * 1000, // TTL of resource
    init: true, // Fetch the resource at nuxt start
    request: {
      method: 'get',
      url: 'http://www.mocky.io/v2/5d9e4c643200002a00329d0a'
    }]
 } // adding this end
},`

thanks @gaetansenn, I suggest to update the doc to be more clear. 👍

**Comment by gaetansenn** [comment]
That was an exemple to show you the way that you need to wrap inside an array.
The correct exemple is :
```
xhrCache: {
  resources: [{
    name: 'my-resource'
    maxAge: 3600 * 1000, // TTL of resource
    init: true, // Fetch the resource at nuxt start
    request: {
      method: 'get',
      url: 'http://www.mocky.io/v2/5d9e4c643200002a00329d0a'
    }
  }]
}
```

I will add more exemple from the Setup section but all the option is explain here -> https://xhr-cache.dewib.com/api/options.html

If you can add a star to the library that would be great too.

Thank you.
